name: voice_chat_poc_client
description: Flutter POC for Azure voice chat (Chunk 3)

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Microphone capture plugin supporting iOS, Android and web.
  record: ^5.1.2

  # WebSocket client for Dart/Flutter.
  web_socket_channel: ^2.4.0

  # Simple state management.
  provider: ^6.1.2

  # For playing audio from the backend
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true